---
name: "Create Backport"
on:
  pull_request:
    types: [ closed ]
env:
  #FIX: org change
  redmine_user_id: dupadhya
  redmine_key: "${{ secrets.REDMINE_KEY }}"
  github_user: ideepika
  github_token: "${{ secrets.GITHUB_TOKEN }}"
  fork_remote: https://github.com/ideepika/ceph.git
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          echo PR #${{ github.event.number }} has been merged
          echo ${{ toJSON(github.event.pull_request.head.sha) }}
          echo ${{ toJSON(github.event.pull_request) }}
          echo ::set-env name=commitmsg_temp::$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "temp " $commitmsg_temp
          echo "real " $commitmsg
          echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD^2)
          echo "github.event.commits[0] " ${{ toJSON(github.event.commits[0]) }}
          echo "github.event.head_commit.message " ${{ toJSON(github.event.head_commit.message) }}
          echo "github.event.commits[0].message " ${{ toJSON(github.event.commits[0].message) }}
          echo "github.event.head_commit.message " ${{ toJSON(github.event.head_commit.message) }}
